### ISSUE TITLE
Part One Tasks

### ISSUE THREAD

**Issue by jkidd86** [tf-ahunter/flight-booker#7]
- [x] Create an Airport model (which just needs an airport code like “SFO” or “NYC”) and use the db/seeds.rb file to create several airports.
- [x] Create a Flight model (with the departure and arrival airport ids, start datetime and flight duration).
- [x] Set up associations so you can ask Flight.first.departure_airport, Flight.first.arrival_airport and get back Airport objects. Same for Airport.first.departing_flights and Airport.first.arriving_flights, which should return a list of Flight objects.
- [x] Seed your database with flights.
- [x] You will search and view results in the same page. Set up your FlightsController and routes to make the Index page (/flights) the root route.
- [x] Create your search form on the /flights index page to submit using a GET (not POST) request back to the same URL.
- [x] Add the four dropdown menus – a list of departure airports, arrival airports, number of passengers (1-4), and a date dropdown for the flight date. The date dropdown should only include dates that have existing flights. Don’t worry about restricting the contents of the airport dropdowns – you’d normally use JavaScript – so just allow the user to select any airport.

**Comment by tf-ahunter** [comment]
Plan:
Delete and recreate all models in order of steps listed above. 
Follow steps listed above while changing methods to use new associations and different models.
